### ISSUE TITLE
Filtering exact item removes it from selection after closing the combo-popup

### ISSUE THREAD

**Issue by jensgoe** [gatanaso/multiselect-combo-box#91] opened 2020-10-28 10:21 UTC
Steps to reproduce:
- Go to the live demo
- Click into the Combobox
- Type in "helium"
- select the "Helium" item -> it is added to the selection. the typed in filter "helium" is appended next to the selection, Thats ok
- click outside the Combobox to close the popup
- Nothing is selected --> Not ok

**Comment by jensgoe** [comment] 2021-03-31 07:37
Do you had a chance to reproduce this issue?

**Comment by gatanaso** [comment] 2022-01-26 21:19
Hi, sorry for the late reply. I guess this was happening in earlier versions. Based on the latest update, which is currently in a pre-release, I was not able to reproduce this issue (i.e. https://multiselect-combo-box.web.app/). Closing for now, but please let me know if it happens again.

**Closed by gatanaso** 2022-01-26 21:19 UTC
