### ISSUE TITLE
Problem running multiple vaading elements with this

### ISSUE THREAD

**Issue by ayya-vimala** [gatanaso/multiselect-combo-box#34] opened 2019-07-31 11:21 UTC
Apart from that the demos don't work because somehow they violate the EU regulations and therefore I get sent to a stop-page from the EU ... :-(

I have a little problem running this element with other vaadin elements on the same page:
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-material-styles" has already been used with this registry
    at Module../node_modules/multiselect-combo-
```
This might be something really simple so can you direct me to what I can do about it?

**Comment by gatanaso** [comment] 2019-07-31 12:25
Hi @ayya-vimala and thank you for raising these issues. 

> Apart from that the demos don't work because somehow they violate the EU regulations and therefore I get sent to a stop-page from the EU ... :-(
> 

This is interesting as I have not encountered any issue regarding EU regulations before. Could you please maybe share more details about how you are trying to access the demos?

> I have a little problem running this element with other vaadin elements on the same page:
> 
> ```
> Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-material-styles" has already been used with this registry
>     at Module../node_modules/multiselect-combo-
> ```

This sounds strange, but I cannot say from the top of my head what could be the cause. Could you please share some source code or a small reproducible example, as it would help greatly in identifying the problem.

BR,
Goran

**Comment by ayya-vimala** [comment] 2019-07-31 12:39
I followed your link on webcomponents.org but also here in your readme file:
https://multiselect-combo-box.firebaseapp.com/demo/

That takes me to a page that looks pretty clumpsy:

![Screenshot from 2019-07-31 14-32-47](https://user-images.githubusercontent.com/49606945/62211953-1c277d00-b3a0-11e9-9911-ed8db7b7e312.png)

But the 'here' directs to the official police website and a form to fill in there. Sorry, I assumed it to be EU legislations because I had a runin with that before but it looks like it's Belgian.
I noticed that although the link is https, the certificate does not seem to work .. I also tried on Chrome and FF. So that might be the problem.

The other problem (regarding Uncaught DomException) I solved by deleting the node_modules folder inside the multiselect-combo-box element so it would take the vaadin-elements from the root folder instead.

**Comment by gatanaso** [comment] 2019-07-31 12:54
> I followed your link on webcomponents.org but also here in your readme file:
> https://multiselect-combo-box.firebaseapp.com/demo/
> 
> That takes me to a page that looks pretty clumpsy:
> 
> ![Screenshot from 2019-07-31 14-32-47](https://user-images.githubusercontent.com/49606945/62211953-1c277d00-b3a0-11e9-9911-ed8db7b7e312.png)
> 
> But the 'here' directs to the official police website and a form to fill in there. Sorry, I assumed it to be EU legislations because I had a runin with that before but it looks like it's Belgian.
> I noticed that although the link is https, the certificate does not seem to work .. I also tried on Chrome and FF. So that might be the problem.
> 

That looks quite interesting, not sure why the demos would be blocked in Belgium 😕 This is how the page looks and it only displays the demos that are also present in the sources:

<img width="1242" alt="Screenshot 2019-07-31 at 15 49 32" src="https://user-images.githubusercontent.com/15094658/62213083-cefcd880-b3aa-11e9-9a22-d6dce4023ec9.png">

Thank you for reporting this, I will try to look into this further and figure out what might be the problem :)

> The other problem (regarding Uncaught DomException) I solved by deleting the node_modules folder inside the multiselect-combo-box element-folder so it would take the vaadin-elements from the root folder instead.
> 
> So the folder structure before npm install of the element was:
> 
> > node_modules
> > ----@vaadin
> > --------vaadin-combo-box
> > --------other vaading wc
> > ----lots of other wc
> 
> And after npm install of the multiselect-combo-box element was:
> 
> > node_modules
> > ----@vaadin
> > --------vaadin-combo-box
> > --------other vaading wc
> > ----lots of other wc
> > ----multiselect-combo-box
> > --------node_modules
> > ------------@vaadin
> > ----------------vaadin-combo-box
> > etc.
> 
> So I just deleted the second node_modules inside the multiselect element.

How did you install the component? Executing `npm install multiselect-combo-box --save` should correctly add it to your `node_modules` folder and it should not contain a `node_modules` of it's own.

**Comment by ayya-vimala** [comment] 2019-07-31 13:00
> How did you install the component? Executing npm install multiselect-combo-box --save should correctly add it to your node_modules folder and it should not contain a node_modules of it's own.

That's exactly what I did and never had a problem like this before. 

If you want me to contact the people behind that stop-site to ask what is going on, let me know.

**Comment by ayya-vimala** [comment] 2019-07-31 13:26
I asked a friend on Linux Mint and they get the same government site. I did get a browser safety warning and had to add an exception. Maybe something to do with SSL config?

**Comment by ayya-vimala** [comment] 2019-07-31 14:47
Some more info ... took some time to get this out. Hope it helps.

> Web sites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for multiselect-combo-box.firebaseapp.com. The certificate is only valid for the following names: *.services.belgium.be, services.belgium.be
> 
> Error code: SSL_ERROR_BAD_CERT_DOMAIN
> 
> View Certificate
> 
> The extended error message reads:
> 
> https://multiselect-combo-box.firebaseapp.com/demo/
> 
> Unable to communicate securely with peer: requested domain name does not match the server's certificate.
> 
> HTTP Strict Transport Security: false
> 
> HTTP Public Key Pinning: false
> 
> Certificate chain:
> 
> 
> -----BEGIN CERTIFICATE-----
> Blah, blah, blah…
> 
> And yes, apparently the SSL certificate is given as being issued to: *.services.belgium.be (or Federale Overheidsdienst Beleid en Ondersteuning in full).
>

**Comment by gatanaso** [comment] 2019-08-01 06:12
Hi @ayya-vimala,

Glad to hear that you are happy with the `multiselect-combo-box` 👍 Also, a huge thank you for taking the time to look deeper into the demos issue, it is very interesting. I will close this ticket and investigate the demos availability separately.

BR,
Goran

**Closed by gatanaso** 2019-08-01 06:12 UTC
Labels: question

**Comment by mvysny** [comment] 2019-08-01 08:36
Sounds like the Belgian authorities blocked *.firebaseapp.com for no apparent reason. @ayya-vimala could you please click on that "here" link in the "STOP" page and drop the authorities a mail as to why that page is blocked?

**Comment by ayya-vimala** [comment] 2019-08-01 08:45
Terve!
I have emailed them. It is the official site of ecops.be 
Will let you know when I get a reply.

**Comment by gatanaso** [comment] 2019-08-01 08:46
@mvysny @ayya-vimala thank you both 🙇 I am looking forward to find what they have to say :)

**Comment by gatanaso** [comment] 2019-08-01 11:01
@ayya-vimala Could you please try to access: https://multiselect-combo-box.web.app/demo/ and let me know if it's still being blocked? 

Thank you,
Goran

**Comment by ayya-vimala** [comment] 2019-08-01 11:40
Hey ... nice work! No, it's working fine. Noticed you took the firebaseapp out.

**Comment by gatanaso** [comment] 2019-08-01 12:06
> Hey ... nice work! No, it's working fine. Noticed you took the firebaseapp out.

Awesome, thanks for taking the time to check the new link 🙇 . I will be updating those accordingly.

BR,
Goran
